// Product Categories - Legacy/Static Data
// Note: Categories should be fetched from database using getCategories() from productsService.js
// This is kept for backward compatibility and fallback

export const categories = [
  {
    id: 'all',
    name: 'Tüm Ürünler',
    slug: 'all',
    icon: '🏪',
  },
  {
    id: 'dogal-taslar',
    name: 'Doğal Taşlar',
    slug: 'dogal-taslar',
    icon: '🪨',
    description: 'Doğal taş ürünleri',
  },
  {
    id: 'somineler',
    name: 'Şömineler',
    slug: 'somineler',
    icon: '🔥',
    description: 'Şömine modelleri',
  },
  {
    id: 'barbeku',
    name: 'Barbekü',
    slug: 'barbeku',
    icon: '🍖',
    description: 'Barbekü sistemleri',
  },
  {
    id: 'firinlar',
    name: 'Fırınlar',
    slug: 'firinlar',
    icon: '🔥',
    description: 'Fırın modelleri',
  },
  {
    id: 'sobalar',
    name: 'Sobalar',
    slug: 'sobalar',
    icon: '🔥',
    description: 'Soba modelleri',
  },
  {
    id: 'tas-aksesuarlar',
    name: 'Taş Aksesuarlar',
    slug: 'tas-aksesuarlar',
    icon: '🗿',
    description: 'Taş aksesuar ürünleri',
  },
];

// Products Data - Gerçek Fotoğraflarla
export const products = [
  // Elektrikli Şömineler (5 ürün)
  {
    id: 1,
    name: '80 cm Elektrikli Şömine',
    category: 'Elektrikli Şömineler',
    categoryId: 'fireplaces',
    image: '/products/elektirikli-somineler/80.png',
    inStock: true,
    badge: 'Yeni',
    description: 'Kompakt tasarımlı 80 cm elektrikli şömine, küçük ve orta boy mekanlara ideal.',
    features: ['LED teknolojisi', 'Uzaktan kumanda', 'Termostat', 'Düşük enerji tüketimi'],
    stock: 15,
  },
  {
    id: 2,
    name: '100 cm Elektrikli Şömine',
    category: 'Elektrikli Şömineler',
    categoryId: 'fireplaces',
    image: '/products/elektirikli-somineler/100.png',
    inStock: true,
    badge: 'Popüler',
    description: 'Orta boy mekanlara uygun 100 cm elektrikli şömine modeli.',
    features: ['Gerçekçi alev efekti', 'Güvenli kullanım', 'Kolay montaj', 'Sessiz çalışma'],
    stock: 20,
  },
  {
    id: 3,
    name: '130 cm Elektrikli Şömine',
    category: 'Elektrikli Şömineler',
    categoryId: 'fireplaces',
    image: '/products/elektirikli-somineler/130.png',
    inStock: true,
    description: 'Geniş mekanlara özel 130 cm elektrikli şömine.',
    features: ['3D alev efekti', 'Ayarlanabilı ısı', 'Modern tasarım', 'Enerji tasarruflu'],
    stock: 12,
  },
  {
    id: 4,
    name: '160 cm Elektrikli Şömine',
    category: 'Elektrikli Şömineler',
    categoryId: 'fireplaces',
    image: '/products/elektirikli-somineler/160.png',
    inStock: true,
    badge: 'Premium',
    description: 'Lüks ve geniş alanlara özel 160 cm premium elektrikli şömine.',
    features: ['Geniş ekran', 'Premium malzeme', 'Akıllı kontrol', 'Uzun ömürlü'],
    stock: 8,
  },
  {
    id: 5,
    name: '200 cm Elektrikli Şömine',
    category: 'Elektrikli Şömineler',
    categoryId: 'fireplaces',
    image: '/products/elektirikli-somineler/200.png',
    inStock: true,
    badge: 'XL',
    description: 'En geniş modelimiz, büyük salonlar ve oteller için 200 cm elektrikli şömine.',
    features: ['Ekstra geniş ekran', 'Profesyonel kalite', 'Özel üretim', 'Garantili'],
    stock: 5,
  },

  // Barbekü Setleri (12 ürün)
  {
    id: 6,
    name: 'Klasik Taş Barbekü Seti',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/348ecce787a940699c90d744716e1ab1-Photoroom.png',
    inStock: true,
    badge: 'En Çok Satan',
    description: 'Dayanıklı taş kaplama ile klasik barbekü seti.',
    features: ['Paslanmaz çelik ızgara', 'Taş kaplama', 'Kolay temizlik', 'Uzun ömürlü'],
    stock: 10,
  },
  {
    id: 7,
    name: 'Modern Bahçe Barbekü',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/90cb0c1cbe6d4aa1a268511de7556088-Photoroom.png',
    inStock: true,
    description: 'Modern tasarımlı bahçe barbekü sistemi.',
    features: ['Şık tasarım', 'Geniş pişirme alanı', 'Pratik kullanım', 'Dayanıklı yapı'],
    stock: 15,
  },
  {
    id: 8,
    name: 'Kompakt Barbekü Seti',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (5).png',
    inStock: true,
    description: 'Küçük bahçeler ve balkonlar için ideal kompakt barbekü.',
    features: ['Alan tasarrufu', 'Kolay montaj', 'Taşınabilir', 'Ekonomik'],
    stock: 25,
  },
  {
    id: 9,
    name: 'Premium Taş Fırın Barbekü',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (7).png',
    inStock: true,
    badge: 'Premium',
    description: 'Taş fırın ve barbekü kombinasyonu, profesyoneller için.',
    features: ['Çift fonksiyon', 'Pizza fırını', 'Geniş kapasite', 'Profesyonel kalite'],
    stock: 6,
  },
  {
    id: 10,
    name: 'Lüks Bahçe Barbekü',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (71).png',
    inStock: true,
    description: 'Şık ve lüks bahçe dekorasyonuna uygun barbekü seti.',
    features: ['Estetik tasarım', 'Kaliteli malzeme', 'Geniş çalışma alanı', 'Dayanıklı'],
    stock: 12,
  },
  {
    id: 11,
    name: 'Deluxe Barbekü Sistemi',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (76).png',
    inStock: true,
    badge: 'Yeni',
    description: 'Tüm özellikleri içeren deluxe barbekü sistemi.',
    features: ['Çok amaçlı', 'Geniş depolama', 'Premium aksesuar', 'Garantili'],
    stock: 8,
  },
  {
    id: 12,
    name: 'Rustik Taş Barbekü',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (79).png',
    inStock: true,
    description: 'Rustik tarza sahip doğal taş barbekü.',
    features: ['Doğal taş', 'El işçiliği', 'Otantik görünüm', 'Sağlam yapı'],
    stock: 10,
  },
  {
    id: 13,
    name: 'Profesyonel Mangal Seti',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (82).png',
    inStock: true,
    description: 'Profesyonel kullanıma uygun mangal seti.',
    features: ['Profesyonel kalite', 'Yüksek kapasite', 'Ticari kullanıma uygun', 'Dayanıklı'],
    stock: 7,
  },
  {
    id: 14,
    name: 'Ekonomik Barbekü',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (84).png',
    inStock: true,
    description: 'Uygun fiyatlı, kaliteli barbekü çözümü.',
    features: ['Ekonomik', 'Pratik', 'Kolay kullanım', 'Garantili'],
    stock: 30,
  },
  {
    id: 15,
    name: 'Bahçe Şömine Barbekü',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (86).png',
    inStock: true,
    description: 'Şömine ve barbekü kombinasyonu.',
    features: ['Çift fonksiyon', 'Isınma + Pişirme', 'Şık tasarım', 'Uzun ömürlü'],
    stock: 9,
  },
  {
    id: 16,
    name: 'Modern Taş Mangal',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (89).png',
    inStock: true,
    description: 'Modern çizgilere sahip taş mangal sistemi.',
    features: ['Çağdaş tasarım', 'Fonksiyonel', 'Kolay temizlik', 'Sağlam'],
    stock: 14,
  },
  {
    id: 17,
    name: 'Villa Barbekü Seti',
    category: 'Barbekü Setleri',
    categoryId: 'bbq',
    image: '/products/barbekuler/image-Photoroom (92).png',
    inStock: true,
    badge: 'Özel',
    description: 'Villalar ve büyük bahçeler için özel tasarım barbekü.',
    features: ['Özel tasarım', 'Geniş alan', 'Premium malzeme', 'Uzun garanti'],
    stock: 5,
  },

  // Taştan Yapılma Ürünler (5 ürün)
  {
    id: 18,
    name: 'Doğal Taş Lavabo',
    category: 'Taştan Yapılma Ürünler',
    categoryId: 'stone-products',
    image: '/products/tas-urunler/IMG-20251103-WA0036.jpg',
    inStock: true,
    badge: 'El Yapımı',
    description: 'Doğal taştan el yapımı özel lavabo.',
    features: ['Benzersiz tasarım', 'Doğal taş', 'Su geçirmez', 'Hijyenik yüzey'],
    stock: 8,
  },
  {
    id: 19,
    name: 'Taş Dekorasyon Ürünü',
    category: 'Taştan Yapılma Ürünler',
    categoryId: 'stone-products',
    image: '/products/tas-urunler/IMG-20251103-WA0037.jpg',
    inStock: true,
    description: 'Özel tasarım taş dekorasyon ürünü.',
    features: ['El işçiliği', 'Dekoratif', 'Dayanıklı', 'Benzersiz'],
    stock: 12,
  },
  {
    id: 20,
    name: 'Doğal Taş Aksesuar',
    category: 'Taştan Yapılma Ürünler',
    categoryId: 'stone-products',
    image: '/products/tas-urunler/IMG-20251103-WA0038.jpg',
    inStock: true,
    description: 'Ev dekorasyonu için doğal taş aksesuar.',
    features: ['Doğal materyal', 'Şık görünüm', 'Uzun ömürlü', 'Kolay bakım'],
    stock: 15,
  },
  {
    id: 21,
    name: 'Taş Sanat Eseri',
    category: 'Taştan Yapılma Ürünler',
    categoryId: 'stone-products',
    image: '/products/tas-urunler/IMG-20251103-WA0039.jpg',
    inStock: true,
    badge: 'Sanat',
    description: 'Usta eller tarafından işlenmiş taş sanat eseri.',
    features: ['Sanat eseri', 'El işçiliği', 'Özel tasarım', 'Koleksiyon değeri'],
    stock: 3,
  },
  {
    id: 22,
    name: 'Modern Taş Ürün',
    category: 'Taştan Yapılma Ürünler',
    categoryId: 'stone-products',
    image: '/products/tas-urunler/IMG-20251103-WA0040.jpg',
    inStock: true,
    description: 'Modern tasarım taş ürün.',
    features: ['Modern tasarım', 'Fonksiyonel', 'Estetik', 'Kaliteli'],
    stock: 10,
  },

  // Taşlar ve Mermerler (28 ürün)
  {
    id: 23,
    name: 'Premium Beyaz Mermer',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0007.jpg',
    inStock: true,
    badge: 'Premium',
    description: 'Yüksek kaliteli beyaz mermer, yapı projeleriniz için ideal.',
    features: ['Doğal taş', 'Su geçirmez', 'Dayanıklı', 'Kolay temizlenir'],
    stock: 50,
  },
  {
    id: 24,
    name: 'Granit Zemin Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0008.jpg',
    inStock: true,
    description: 'Dayanıklı granit taş, zemin kaplama için mükemmel.',
    features: ['Aşınmaya dayanıklı', 'Donmaz', 'Uzun ömürlü', 'Kaymaz yüzey'],
    stock: 100,
  },
  {
    id: 25,
    name: 'Traverten Doğal Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0009.jpg',
    inStock: true,
    description: 'Doğal görünümlü traverten taş, duvar ve zemin için.',
    features: ['Doğal doku', 'Sıcak tonlar', 'Kaymazlık özelliği', 'Estetik'],
    stock: 75,
  },
  {
    id: 26,
    name: 'Siyah Mermer Plaka',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0010.jpg',
    inStock: true,
    badge: 'Lüks',
    description: 'Şık siyah mermer, lüks mekanlara özel.',
    features: ['Lüks görünüm', 'Parlak yüzey', 'Hijyenik', 'Premium kalite'],
    stock: 30,
  },
  {
    id: 27,
    name: 'Oniks Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0011.jpg',
    inStock: true,
    badge: 'Özel',
    description: 'Benzersiz damar desenli oniks taş.',
    features: ['Benzersiz desenler', 'Işık geçirgen', 'Dekoratif', 'Değerli'],
    stock: 15,
  },
  {
    id: 28,
    name: 'Krem Mermer',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0012.jpg',
    inStock: true,
    description: 'Sıcak tonlu krem mermer.',
    features: ['Sıcak ton', 'Klasik', 'Zamansız', 'Çok yönlü'],
    stock: 60,
  },
  {
    id: 29,
    name: 'Gri Granit',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0013.jpg',
    inStock: true,
    description: 'Modern gri tonlu granit taş.',
    features: ['Modern renk', 'Dayanıklı', 'Leke tutmaz', 'Profesyonel'],
    stock: 80,
  },
  {
    id: 30,
    name: 'Bej Traverten',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0014.jpg',
    inStock: true,
    description: 'Doğal bej traverten taş.',
    features: ['Doğal renk', 'Mat yüzey', 'Kaymaz', 'Dış mekan uyumlu'],
    stock: 90,
  },
  {
    id: 31,
    name: 'Mozaik Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0015.jpg',
    inStock: true,
    description: 'Dekoratif mozaik taş ürünü.',
    features: ['Mozaik desen', 'Sanatsal', 'Özel tasarım', 'Dekoratif'],
    stock: 40,
  },
  {
    id: 32,
    name: 'Mermer Plaka Set',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0016.jpg',
    inStock: true,
    description: 'Çeşitli boyutlarda mermer plaka seti.',
    features: ['Farklı boyutlar', 'Ekonomik set', 'Kaliteli', 'Hazır kullanım'],
    stock: 25,
  },
  {
    id: 33,
    name: 'Doğal Kaya Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0017.jpg',
    inStock: true,
    description: 'Ham doğal kaya taşı.',
    features: ['Doğal form', 'Ham yüzey', 'Rustik', 'Bahçe düzenleme'],
    stock: 100,
  },
  {
    id: 34,
    name: 'Cilalı Mermer',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0018.jpg',
    inStock: true,
    badge: 'Parlak',
    description: 'Yüksek cila parlak mermer.',
    features: ['Ayna gibi parlak', 'Prestijli', 'İç mekan', 'Lüks'],
    stock: 35,
  },
  {
    id: 35,
    name: 'Kumtaşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0019.jpg',
    inStock: true,
    description: 'Doğal kumtaşı kaplama malzemesi.',
    features: ['Doğal doku', 'Sıcak renk', 'Dış cephe uygun', 'Dayanıklı'],
    stock: 70,
  },
  {
    id: 36,
    name: 'Slate Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0020.jpg',
    inStock: true,
    description: 'Modern slate (arduvaz) taş.',
    features: ['Modern', 'Mat yüzey', 'Çizgi desenleri', 'Şık'],
    stock: 55,
  },
  {
    id: 37,
    name: 'Kuvarsit Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0021.jpg',
    inStock: true,
    badge: 'Sağlam',
    description: 'Ultra dayanıklı kuvarsit taş.',
    features: ['Çok dayanıklı', 'Çizilmeye karşı dirençli', 'Leke tutmaz', 'Premium'],
    stock: 20,
  },
  {
    id: 38,
    name: 'Patlatma Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0022.jpg',
    inStock: true,
    description: 'Rustik patlatma yüzey taş.',
    features: ['Rustik yüzey', 'Kaymaz', 'Dış mekan', 'Otantik'],
    stock: 85,
  },
  {
    id: 39,
    name: 'Bazalt Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0023.jpg',
    inStock: true,
    description: 'Koyu renkli bazalt taş.',
    features: ['Koyu renk', 'Yüksek yoğunluk', 'Dayanıklı', 'Modern'],
    stock: 45,
  },
  {
    id: 40,
    name: 'Kalker Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0024.jpg',
    inStock: true,
    description: 'Açık renkli kalker taşı.',
    features: ['Açık renk', 'Doğal', 'Ekonomik', 'Çok amaçlı'],
    stock: 95,
  },
  {
    id: 41,
    name: 'Kayrak Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0025.jpg',
    inStock: true,
    description: 'Geleneksel kayrak taşı.',
    features: ['Geleneksel', 'Kaymaz', 'Dış mekan ideal', 'Ekonomik'],
    stock: 110,
  },
  {
    id: 42,
    name: 'Andezit Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0026.jpg',
    inStock: true,
    description: 'Volkanik andezit taş.',
    features: ['Volkanik kökenli', 'Çok sağlam', 'Hava koşullarına dayanıklı', 'Profesyonel'],
    stock: 40,
  },
  {
    id: 43,
    name: 'Mermermsi Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0027.jpg',
    inStock: true,
    description: 'Mermer görünümlü taş ürün.',
    features: ['Mermer görünümü', 'Ekonomik alternatif', 'Dayanıklı', 'Pratik'],
    stock: 60,
  },
  {
    id: 44,
    name: 'Kristal Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0028.jpg',
    inStock: true,
    badge: 'Özel',
    description: 'Kristal yapılı özel taş.',
    features: ['Kristal yapı', 'Işıltılı', 'Dekoratif', 'Değerli'],
    stock: 10,
  },
  {
    id: 45,
    name: 'Doğal Karo Taş',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0029.jpg',
    inStock: true,
    description: 'Karo formunda doğal taş.',
    features: ['Hazır karo', 'Kolay uygulama', 'Standart ölçü', 'Pratik'],
    stock: 120,
  },
  {
    id: 46,
    name: 'Dekoratif Taş Panel',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0030.jpg',
    inStock: true,
    description: 'Duvar kaplama için dekoratif taş panel.',
    features: ['Panel sistem', 'Kolay montaj', 'Dekoratif', 'Modern'],
    stock: 50,
  },
  {
    id: 47,
    name: 'Çakıl Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0031.jpg',
    inStock: true,
    description: 'Bahçe düzenleme için çakıl taşı.',
    features: ['Bahçe süslemesi', 'Doğal renkler', 'Farklı boyutlar', 'Ekonomik'],
    stock: 200,
  },
  {
    id: 48,
    name: 'Bordür Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0032.jpg',
    inStock: true,
    description: 'Kenar düzenleme için bordür taşı.',
    features: ['Bordür çözümü', 'Sağlam', 'Uzun ömürlü', 'Fonksiyonel'],
    stock: 150,
  },
  {
    id: 49,
    name: 'Duvar Taşı',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0033.jpg',
    inStock: true,
    description: 'Duvar örme ve kaplama taşı.',
    features: ['Duvar yapımı', 'Sağlam yapı', 'Doğal görünüm', 'Dayanıklı'],
    stock: 180,
  },
  {
    id: 50,
    name: 'Karma Taş Koleksiyonu',
    category: 'Taşlar ve Mermerler',
    categoryId: 'stones-marbles',
    image: '/products/taslar/IMG-20251103-WA0034.jpg',
    inStock: true,
    badge: 'Set',
    description: 'Farklı taş türlerinden oluşan karma koleksiyon.',
    features: ['Karma set', 'Çeşitli türler', 'Ekonomik', 'Dekoratif'],
    stock: 30,
  },
];

// Helper function to get products by category
export const getProductsByCategory = (categoryId) => {
  if (categoryId === 'all') return products;
  return products.filter((product) => product.categoryId === categoryId);
};

// Helper function to get product by ID
export const getProductById = (id) => {
  return products.find((product) => product.id === parseInt(id));
};

// Helper function to get featured products
export const getFeaturedProducts = (count = 8) => {
  return products
    .filter((product) => product.badge)
    .slice(0, count);
};

// Helper function to get random products
export const getRandomProducts = (count = 4) => {
  const shuffled = [...products].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};
